steps:
- task: AzureFileCopy@2
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: rgomezj.Freelance.meServerles/rgomezj.Freelance.meServerless.UI/wwwroot

    azureSubscription: 'Pay-As-You-Go Dev/Test (af2792d7-bb35-4339-9cc7-5bb060db3f12)'

    Destination: AzureBlob

    storage: rogergomezstaging

    ContainerName: '$web'
